### ISSUE TITLE
Is Sonic Possible?

### ISSUE THREAD

**Issue by EndurusPrime** [libsm64/libsm64#46]
I am Probably Not smart enough to do this myself, but I felt I should ask anyways.
Is it Possible to do a Similar thing to this with a Decomplication of Sonic Adventure or SADX? 
I'm pretty sure that Plenty of people would wanna do the same thing with sonic as they did with this.
So, my only question... Is it even possible?

**Comment by jaburns** [comment]
It would theoretically be possible, but it doesn't look like there's a sufficiently advanced decompilation of that game. I was only really able to do this with SM64 in a reasonable time because the decomp got to a stage where I could just read and understand the code without much experience with sm64 hacking. The sonic decomp looks like it's still huge piles of unnamed objects and addresses. So maybe eventually someone could, but not soon I think.
